### ISSUE TITLE
config/config.js下proxy是配置跨域吗

### ISSUE THREAD

**Issue by 378406712** [mpw0311/antd-umi-sys#148]
本地3001端口配置跨域无效，试了网上很多说的方法了，有办法吗

**Comment by mpw0311** [comment]
是的，proxy是本地服务请求代理，https://www.webpackjs.com/configuration/dev-server/#devserver-proxy

**Comment by 378406712** [comment]
配了本地后端接口，好像还是没用，/api还是没有替换本地后端接口

---原始邮件---
发件人: "M"<notifications@github.com&gt;
发送时间: 2020年10月27日(周二) 晚上6:20
收件人: "mpw0311/antd-umi-sys"<antd-umi-sys@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Clover"<378406712@qq.com&gt;;
主题: Re: [mpw0311/antd-umi-sys] config/config.js下proxy是配置跨域吗 (#148)




 
是的，proxy是本地服务请求代理，https://www.webpackjs.com/configuration/dev-server/#devserver-proxy

**Comment by 378406712** [comment]
解决了，network中Request虽然没有改变请求地址，但是后台那边的确请求到了
