### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by SynChron1zed** [mpw0311/antd-umi-sys#33]
![image](https://user-images.githubusercontent.com/18717051/48670634-828fa680-eb55-11e8-8b74-56c8659813ff.png)

**Comment by SynChron1zed** [comment]
按提示走了一遍也不行

**Comment by mpw0311** [comment]
umi-plugin-react安装了么，yarn add umi-plugin-react --dev  试试

**Comment by mpw0311** [comment]
缺少依赖包umi-plugin-react，安装一下
