### ISSUE TITLE
关于models里面的global.js

### ISSUE THREAD

**Issue by leeycode** [mpw0311/antd-umi-sys#36]
1.请问`* getSysInfo()中,let res = yield select(({ global }) => global.result);`我找了store里面的global中并没有result啊，为什么要怎么写？

2.`const { rows: keys } = menus;
    const { rows: orginalRows } = orginalData;`
请问这种写法是什么语法？
新手请楼主不吝赐教

**Comment by leeycode** [comment]
`let res = yield select(({ global }) => global.result)为undefined`

**Comment by mpw0311** [comment]
问题已修复，thanks
